### PR TITLE
Save info when dumped and loaded by Marshal

### PR DESCRIPTION
**Pull request by wildmaples**
Previously, ROS did not play well when being dump and loaded with Marshal because the options from ROS did not translate through the serialization. This change saves the information through marshal_dump and then reassigns the information to ROS instance when the object is loaded.

(ideally) Fix: https://github.com/aetherknight/recursive-open-struct/issues/71

### CODE REVIEW

**Comment by wildmaples** [comment]
Closing due to repo's inactivity

**Comment by Jack12816** [comment]
@wildmaples Could you open this again? Looks like @aetherknight had time this year to perform some interactions, and this is still an issue on a 50 mio downloads gem. :(

**Comment by aetherknight** [comment]
I’ll look into reviewing and merging this tonight

**Comment by aetherknight** [comment]
Released as part of 1.3.0

**Comment by Jack12816** [comment]
Thank you very much! :heart:

**Comment by aetherknight** [comment]
@Jack12816 @wildmaples FYI, since this is an API-breaking change, I have released 1.3.1 that reverts this change, but it's re-added in a version 2.0.0, in order to preserve semver. (See #79 for more discussion)

**Comment by Jack12816** [comment]
Thank you!

**Pull request merged**
