### PR TITLE
Use modifiable? (thanks to Ben Langfeld)

### LINKED ISSUE #62: tests fail with ruby version 2.7 NoMethodError: undefined method `[]=' for nil:NilClass
Tests are failing with ruby 2.7

```
44) RecursiveOpenStruct recursive behavior recursing over arrays modifying an array and recursing over it after appending a hash to an array can have new values be set
      Failure/Error: modifiable[new_ostruct_member!($1.to_sym)] = args[0]
      
      NoMethodError:
        undefined method `[]=' for nil:NilClass
      # ./lib/recursive_open_struct.rb:82:in `method_missing'
      # ./spec/recursive_open_struct/recursion_spec.rb:272:in `block (6 levels) in <top (required)>'

Finished in 0.03504 seconds (files took 0.21339 seconds to load)
114 examples, 44 failures
```

### PR DESCRIPTION
**Pull request by pravi**
This fixes #62 and brings ruby 2.7 compatibility

### CODE REVIEW

**Comment by benlangfeld** [comment]
See also https://github.com/aetherknight/recursive-open-struct/pull/63

**Comment by benlangfeld** [comment]
@pravi You'll need to alias if the method doesn't exist for backward compatibility with old rubies, unless @aetherknight is happy to drop support for EOL rubies (< 2.4).

**Comment by cben** [comment]
For others looking: This is an internal OpenStruct method, was renamed and made `private` in https://github.com/ruby/ruby/commit/7c89ca5431c370496e0f1ee3761781e6d74e57b4 since 2.4.0.  
But that commit still aliased to old names.  Those aliases were removed in https://github.com/ruby/ruby/commit/dbcc224f3883c810049ef620fac8a1b59bde2e69 since 2.7.0.

- Using `modifiable?` also breaks on jruby-9.1.  I don't know much about it but according to https://www.jruby.org/download, 9.1 tracks ruby 2.3 and 9.2 tracks 2.5.  Is it OK to also drop 9.1?

- @aetherknight Do you consider `modifiable` a public part of RecursiveOpenStruct interface?

If you want to support both, could test `respond_to?(:modifiable?, true)`.

**Comment by matti** [comment]
how could we get this moving? the best k8s client 2.7 support depends on this

**Comment by aetherknight** [comment]
I'm happy to drop support for unsupported versions of Ruby/JRuby. It looks like this change works fine on 2.4 and later, so I'll get this merged and get a release out soon.

**Comment by aetherknight** [comment]
I just released v1.1.1 which incorporates this PR, plus continues to support older Ruby versions. (JRuby's stable release still tracks 2.3.x features)

**Pull request merged**
